version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: site
      MYSQL_ROOT_PASSWORD: mudarSenh@
    ports:
      - "3306:3306"
